### ISSUE TITLE
Bundle libargon2

### ISSUE THREAD

**Issue by bwesterb** [flamewow/argon2_py#2]
As `libargon2` is not available in a lot of package managers, it would be helpful to bundle it with this PyPI package.

**Comment by flamewow** [comment]
Try:
pip install argon2
Curently it works on linux (ubuntu), not sure about OSX (might be some problems with installation), like 100% not working with Windows.

**Comment by bwesterb** [comment]
Ah, it's bundled already!  Sorry, didn't see that.  I'll create a new issue for the problem I hit.
